### ISSUE TITLE
iOS supported version check is wrong

### ISSUE THREAD

**Issue by NicolaVerbeeck** [icapps/flutter_secure_file_storage#5]
It just checks != 12 so it would also match below 12!

**Comment by ikbendewilliam** [comment]
Correct, we only check version 12 for our app, since it's the only < 13 iOS version that is supported. But the package should also check 8-11

**Comment by ikbendewilliam** [comment]
see also #3

**Comment by vanlooverenkoen** [comment]
duplicate of #3
