### ISSUE TITLE
Delete throws an error when file not found

### ISSUE THREAD

**Issue by ikbendewilliam** [icapps/flutter_secure_file_storage#6]
If we don't have the file or a specific value, we should ignore the error and return a success, since the file does not exists and that's the point of deleting it 😁 
```
I/flutter (25796): 11:20:23.674 FileSystemException: Cannot delete file, path = '/data/user/0/package_name/app_flutter/cmatc3RlXaNvb4ZpZ19vdmVycmlkZQ==.enc' (OS Error: No such file or directory, errno = 2)
```

**Comment by NicolaVerbeeck** [comment]
From what I can see in the sources, this has been fixed already. Closing
